version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'blog-dependencies-{{ checksum "package.json" }}'
            - blog-dependencies-
      - run:
          name: Install packages
          command: yarn install
      - run:
          name: Build and push to gh-pages branch
          command: yarn deploy
